// Generated by Supabase CLI / MCP. Regenerate with:
//   supabase gen types typescript --project-id bvwumzzuvubiacueftbz > database.types.ts
// Do not edit by hand — changes will be overwritten on next regenerate.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: '14.4';
  };
  public: {
    Tables: {
      ai_usage_log: {
        Row: {
          created_at: string | null;
          endpoint: string;
          id: string;
          tokens_used: number | null;
          user_id: string;
        };
        Insert: {
          created_at?: string | null;
          endpoint: string;
          id?: string;
          tokens_used?: number | null;
          user_id: string;
        };
        Update: {
          created_at?: string | null;
          endpoint?: string;
          id?: string;
          tokens_used?: number | null;
          user_id?: string;
        };
        Relationships: [];
      };
      connections: {
        Row: {
          canvas_api_token: string | null;
          canvas_api_token_encrypted: string | null;
          consecutive_errors: number | null;
          created_at: string;
          id: string;
          last_error_message: string | null;
          last_synced_at: string | null;
          oauth_token: string | null;
          oauth_token_encrypted: string | null;
          platform: string;
          refresh_token: string | null;
          refresh_token_encrypted: string | null;
          status: string;
          user_id: string;
        };
        Insert: {
          canvas_api_token?: string | null;
          canvas_api_token_encrypted?: string | null;
          consecutive_errors?: number | null;
          created_at?: string;
          id?: string;
          last_error_message?: string | null;
          last_synced_at?: string | null;
          oauth_token?: string | null;
          oauth_token_encrypted?: string | null;
          platform: string;
          refresh_token?: string | null;
          refresh_token_encrypted?: string | null;
          status?: string;
          user_id: string;
        };
        Update: {
          canvas_api_token?: string | null;
          canvas_api_token_encrypted?: string | null;
          consecutive_errors?: number | null;
          created_at?: string;
          id?: string;
          last_error_message?: string | null;
          last_synced_at?: string | null;
          oauth_token?: string | null;
          oauth_token_encrypted?: string | null;
          platform?: string;
          refresh_token?: string | null;
          refresh_token_encrypted?: string | null;
          status?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      conversations: {
        Row: {
          created_at: string;
          id: string;
          messages: Json;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          messages?: Json;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          messages?: Json;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      fixed_events: {
        Row: {
          color: string | null;
          created_at: string;
          days_of_week: number[];
          end_time: string;
          id: string;
          recurrence_rule: string | null;
          start_time: string;
          title: string;
          user_id: string;
        };
        Insert: {
          color?: string | null;
          created_at?: string;
          days_of_week?: number[];
          end_time: string;
          id?: string;
          recurrence_rule?: string | null;
          start_time: string;
          title: string;
          user_id: string;
        };
        Update: {
          color?: string | null;
          created_at?: string;
          days_of_week?: number[];
          end_time?: string;
          id?: string;
          recurrence_rule?: string | null;
          start_time?: string;
          title?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      guardrails: {
        Row: {
          active: boolean;
          created_at: string;
          id: string;
          rule_type: string;
          user_id: string;
          value: Json;
        };
        Insert: {
          active?: boolean;
          created_at?: string;
          id?: string;
          rule_type: string;
          user_id: string;
          value?: Json;
        };
        Update: {
          active?: boolean;
          created_at?: string;
          id?: string;
          rule_type?: string;
          user_id?: string;
          value?: Json;
        };
        Relationships: [];
      };
      scheduled_blocks: {
        Row: {
          created_at: string;
          day: string;
          end_time: string;
          id: string;
          start_time: string;
          status: string;
          task_id: string | null;
          updated_at: string | null;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          day: string;
          end_time: string;
          id?: string;
          start_time: string;
          status?: string;
          task_id?: string | null;
          updated_at?: string | null;
          user_id: string;
        };
        Update: {
          created_at?: string;
          day?: string;
          end_time?: string;
          id?: string;
          start_time?: string;
          status?: string;
          task_id?: string | null;
          updated_at?: string | null;
          user_id?: string;
        };
        Relationships: [];
      };
      sync_log: {
        Row: {
          completed_at: string | null;
          connection_id: string;
          error_message: string | null;
          id: string;
          started_at: string | null;
          status: string;
          tasks_found: number | null;
          tasks_new: number | null;
          tasks_updated: number | null;
          user_id: string;
        };
        Insert: {
          completed_at?: string | null;
          connection_id: string;
          error_message?: string | null;
          id?: string;
          started_at?: string | null;
          status: string;
          tasks_found?: number | null;
          tasks_new?: number | null;
          tasks_updated?: number | null;
          user_id: string;
        };
        Update: {
          completed_at?: string | null;
          connection_id?: string;
          error_message?: string | null;
          id?: string;
          started_at?: string | null;
          status?: string;
          tasks_found?: number | null;
          tasks_new?: number | null;
          tasks_updated?: number | null;
          user_id?: string;
        };
        Relationships: [];
      };
      task_completions: {
        Row: {
          actual_minutes: number;
          completed_at: string;
          estimated_minutes: number;
          id: string;
          task_id: string;
          user_feedback: string | null;
          user_id: string;
        };
        Insert: {
          actual_minutes: number;
          completed_at?: string;
          estimated_minutes: number;
          id?: string;
          task_id: string;
          user_feedback?: string | null;
          user_id: string;
        };
        Update: {
          actual_minutes?: number;
          completed_at?: string;
          estimated_minutes?: number;
          id?: string;
          task_id?: string;
          user_feedback?: string | null;
          user_id?: string;
        };
        Relationships: [];
      };
      tasks: {
        Row: {
          created_at: string;
          deleted_at: string | null;
          description: string | null;
          difficulty: number;
          due_date: string;
          estimated_minutes: number;
          external_id: string | null;
          id: string;
          source: string;
          status: string;
          subject: string;
          task_type: string;
          title: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          deleted_at?: string | null;
          description?: string | null;
          difficulty?: number;
          due_date: string;
          estimated_minutes?: number;
          external_id?: string | null;
          id?: string;
          source: string;
          status?: string;
          subject: string;
          task_type: string;
          title: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          deleted_at?: string | null;
          description?: string | null;
          difficulty?: number;
          due_date?: string;
          estimated_minutes?: number;
          external_id?: string | null;
          id?: string;
          source?: string;
          status?: string;
          subject?: string;
          task_type?: string;
          title?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      users: {
        Row: {
          created_at: string;
          daily_trigger_time: string;
          display_name: string | null;
          email: string;
          expo_push_token: string | null;
          grade_level: number | null;
          id: string;
          notifications_enabled: boolean | null;
          onboarding_answers: Json | null;
          onboarding_step: number;
          timezone: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          daily_trigger_time?: string;
          display_name?: string | null;
          email: string;
          expo_push_token?: string | null;
          grade_level?: number | null;
          id: string;
          notifications_enabled?: boolean | null;
          onboarding_answers?: Json | null;
          onboarding_step?: number;
          timezone?: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          daily_trigger_time?: string;
          display_name?: string | null;
          email?: string;
          expo_push_token?: string | null;
          grade_level?: number | null;
          id?: string;
          notifications_enabled?: boolean | null;
          onboarding_answers?: Json | null;
          onboarding_step?: number;
          timezone?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      users_due_for_sync: {
        Row: {
          connection_id: string | null;
          connection_status: string | null;
          daily_trigger_time: string | null;
          expo_push_token: string | null;
          last_synced_local_date: string | null;
          local_now: string | null;
          notifications_enabled: boolean | null;
          timezone: string | null;
          today_local_date: string | null;
          user_id: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      check_ai_rate_limit: {
        Args: { p_endpoint: string; p_max_per_hour?: number; p_user_id: string };
        Returns: boolean;
      };
      decrypt_token: { Args: { ciphertext: string }; Returns: string };
      encrypt_token: { Args: { plaintext: string }; Returns: string };
      find_users_to_sync: {
        Args: Record<string, never>;
        Returns: { user_id: string }[];
      };
      fire_daily_pipeline: { Args: Record<string, never>; Returns: undefined };
      upsert_classroom_connection: {
        Args: { p_provider_refresh_token: string; p_provider_token: string };
        Returns: string;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
