// Generated by Supabase CLI / MCP. Regenerate with:
//   supabase gen types typescript --project-id ffljbfhljymppxkbbgtz > database.types.ts
// Do not edit by hand — changes will be overwritten on next regenerate.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.1';
  };
  public: {
    Tables: {
      connections: {
        Row: {
          canvas_api_token: string | null;
          canvas_base_url: string | null;
          created_at: string;
          id: string;
          last_synced_at: string | null;
          oauth_token: string;
          platform: Database['public']['Enums']['connection_platform'];
          refresh_token: string;
          status: Database['public']['Enums']['connection_status'];
          user_id: string;
        };
        Insert: {
          canvas_api_token?: string | null;
          canvas_base_url?: string | null;
          created_at?: string;
          id?: string;
          last_synced_at?: string | null;
          oauth_token: string;
          platform: Database['public']['Enums']['connection_platform'];
          refresh_token: string;
          status?: Database['public']['Enums']['connection_status'];
          user_id: string;
        };
        Update: {
          canvas_api_token?: string | null;
          canvas_base_url?: string | null;
          created_at?: string;
          id?: string;
          last_synced_at?: string | null;
          oauth_token?: string;
          platform?: Database['public']['Enums']['connection_platform'];
          refresh_token?: string;
          status?: Database['public']['Enums']['connection_status'];
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'connections_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      conversations: {
        Row: {
          created_at: string;
          id: string;
          messages: Json;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          messages?: Json;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          messages?: Json;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'conversations_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      fixed_events: {
        Row: {
          color: string | null;
          created_at: string;
          days_of_week: number[];
          end_time: string;
          id: string;
          recurrence_rule: string | null;
          start_time: string;
          title: string;
          user_id: string;
        };
        Insert: {
          color?: string | null;
          created_at?: string;
          days_of_week: number[];
          end_time: string;
          id?: string;
          recurrence_rule?: string | null;
          start_time: string;
          title: string;
          user_id: string;
        };
        Update: {
          color?: string | null;
          created_at?: string;
          days_of_week?: number[];
          end_time?: string;
          id?: string;
          recurrence_rule?: string | null;
          start_time?: string;
          title?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'fixed_events_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      guardrails: {
        Row: {
          active: boolean;
          created_at: string;
          id: string;
          rule_type: Database['public']['Enums']['guardrail_rule_type'];
          user_id: string;
          value: Json;
        };
        Insert: {
          active?: boolean;
          created_at?: string;
          id?: string;
          rule_type: Database['public']['Enums']['guardrail_rule_type'];
          user_id: string;
          value: Json;
        };
        Update: {
          active?: boolean;
          created_at?: string;
          id?: string;
          rule_type?: Database['public']['Enums']['guardrail_rule_type'];
          user_id?: string;
          value?: Json;
        };
        Relationships: [
          {
            foreignKeyName: 'guardrails_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      scheduled_blocks: {
        Row: {
          created_at: string;
          day: string;
          end_time: string;
          id: string;
          start_time: string;
          status: Database['public']['Enums']['block_status'];
          task_id: string | null;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          day: string;
          end_time: string;
          id?: string;
          start_time: string;
          status?: Database['public']['Enums']['block_status'];
          task_id?: string | null;
          user_id: string;
        };
        Update: {
          created_at?: string;
          day?: string;
          end_time?: string;
          id?: string;
          start_time?: string;
          status?: Database['public']['Enums']['block_status'];
          task_id?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'scheduled_blocks_task_id_fkey';
            columns: ['task_id'];
            isOneToOne: false;
            referencedRelation: 'tasks';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'scheduled_blocks_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      task_completions: {
        Row: {
          actual_minutes: number;
          completed_at: string;
          estimated_minutes: number;
          id: string;
          task_id: string;
          user_feedback: Database['public']['Enums']['user_feedback'] | null;
          user_id: string;
        };
        Insert: {
          actual_minutes: number;
          completed_at?: string;
          estimated_minutes: number;
          id?: string;
          task_id: string;
          user_feedback?: Database['public']['Enums']['user_feedback'] | null;
          user_id: string;
        };
        Update: {
          actual_minutes?: number;
          completed_at?: string;
          estimated_minutes?: number;
          id?: string;
          task_id?: string;
          user_feedback?: Database['public']['Enums']['user_feedback'] | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'task_completions_task_id_fkey';
            columns: ['task_id'];
            isOneToOne: false;
            referencedRelation: 'tasks';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'task_completions_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      tasks: {
        Row: {
          created_at: string;
          description: string | null;
          difficulty: number;
          due_date: string;
          estimated_minutes: number;
          external_id: string | null;
          id: string;
          source: Database['public']['Enums']['task_source'];
          status: Database['public']['Enums']['task_status'];
          subject: string;
          task_type: Database['public']['Enums']['task_type'];
          title: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          description?: string | null;
          difficulty: number;
          due_date: string;
          estimated_minutes: number;
          external_id?: string | null;
          id?: string;
          source: Database['public']['Enums']['task_source'];
          status?: Database['public']['Enums']['task_status'];
          subject?: string;
          task_type?: Database['public']['Enums']['task_type'];
          title: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          description?: string | null;
          difficulty?: number;
          due_date?: string;
          estimated_minutes?: number;
          external_id?: string | null;
          id?: string;
          source?: Database['public']['Enums']['task_source'];
          status?: Database['public']['Enums']['task_status'];
          subject?: string;
          task_type?: Database['public']['Enums']['task_type'];
          title?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'tasks_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      users: {
        Row: {
          created_at: string;
          daily_trigger_time: string;
          display_name: string;
          email: string;
          entitlement_status: Database['public']['Enums']['entitlement_status'];
          entitlement_updated_at: string | null;
          first_schedule_rendered_at: string | null;
          grade_level: number;
          id: string;
          last_entitlement_event_id: string | null;
          onboarding_answers: Json;
          onboarding_step: number;
          push_token: string | null;
          timezone: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          daily_trigger_time?: string;
          display_name?: string;
          email: string;
          entitlement_status?: Database['public']['Enums']['entitlement_status'];
          entitlement_updated_at?: string | null;
          first_schedule_rendered_at?: string | null;
          grade_level?: number;
          id: string;
          last_entitlement_event_id?: string | null;
          onboarding_answers?: Json;
          onboarding_step?: number;
          push_token?: string | null;
          timezone?: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          daily_trigger_time?: string;
          display_name?: string;
          email?: string;
          entitlement_status?: Database['public']['Enums']['entitlement_status'];
          entitlement_updated_at?: string | null;
          first_schedule_rendered_at?: string | null;
          grade_level?: number;
          id?: string;
          last_entitlement_event_id?: string | null;
          onboarding_answers?: Json;
          onboarding_step?: number;
          push_token?: string | null;
          timezone?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      waitlist: {
        Row: {
          created_at: string | null;
          email: string | null;
          id: string | null;
          name: string | null;
          notes: string | null;
          referral_code: string | null;
          source: string | null;
        };
        Insert: {
          created_at?: string | null;
          email?: string | null;
          id?: string | null;
          name?: string | null;
          notes?: string | null;
          referral_code?: string | null;
          source?: string | null;
        };
        Update: {
          created_at?: string | null;
          email?: string | null;
          id?: string | null;
          name?: string | null;
          notes?: string | null;
          referral_code?: string | null;
          source?: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      users_due_for_daily_trigger: {
        Args: { now_utc: string };
        Returns: {
          id: string;
        }[];
      };
    };
    Enums: {
      block_status: 'shadow' | 'approved' | 'completed' | 'rejected';
      connection_platform: 'google_classroom' | 'canvas';
      connection_status: 'active' | 'expired' | 'error';
      entitlement_status: 'free_preview' | 'trialing' | 'pro' | 'lapsed';
      guardrail_rule_type: 'no_work_after' | 'buffer_after_event' | 'max_hours_per_day';
      task_source: 'google_classroom' | 'canvas' | 'manual' | 'photo';
      task_status: 'pending' | 'scheduled' | 'in_progress' | 'completed';
      task_type:
        | 'essay'
        | 'problem_set'
        | 'reading'
        | 'project'
        | 'study_guide'
        | 'quiz_prep'
        | 'other';
      user_feedback: 'too_long' | 'about_right' | 'too_short';
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] &
        DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] &
        DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema['Enums']
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      block_status: ['shadow', 'approved', 'completed', 'rejected'],
      connection_platform: ['google_classroom', 'canvas'],
      connection_status: ['active', 'expired', 'error'],
      entitlement_status: ['free_preview', 'trialing', 'pro', 'lapsed'],
      guardrail_rule_type: ['no_work_after', 'buffer_after_event', 'max_hours_per_day'],
      task_source: ['google_classroom', 'canvas', 'manual', 'photo'],
      task_status: ['pending', 'scheduled', 'in_progress', 'completed'],
      task_type: ['essay', 'problem_set', 'reading', 'project', 'study_guide', 'quiz_prep', 'other'],
      user_feedback: ['too_long', 'about_right', 'too_short'],
    },
  },
} as const;
